### ISSUE TITLE
Cambiar a             @foreach (var tecnico in ListaTecnicos)

### ISSUE THREAD

**Issue by enelramon** [SamyJp23/RegistroTecnico#3]
https://github.com/SamyJp23/RegistroTecnicos/blob/7be0f7ec5f0b099e1c1e27593f3d2a4f0456b11e/RegistroTecnicos/Components/Pages/Registros/Index.razor#L55

**Comment by SamyJp23** [comment]
Resolviendo el issue cambiando la palabra tecnicos del foreach a singular
