### ISSUE TITLE
Debes poner la ruta "Tecnico/Index" de esta forma podrás tener más registros 

### ISSUE THREAD

**Issue by enelramon** [SamyJp23/RegistroTecnico#4]
https://github.com/SamyJp23/RegistroTecnicos/blob/7be0f7ec5f0b099e1c1e27593f3d2a4f0456b11e/RegistroTecnicos/Components/Pages/Registros/Index.razor#L2

**Comment by SamyJp23** [comment]
Resolviendo el issue agregando /Tecnico en la ruta de la pagina

**Comment by SamyJp23** [comment]
Resolviendo el issue agregando /Tecnico a la ruta de la pagina
